version: "3.8"

services:
  ai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPEECHMATICS_API_TOKEN=${SPEECHMATICS_API_TOKEN}
      - SM_URL=${SM_URL:-wss://eu2.rt.speechmatics.com/v2}
      - REPORT_TEMPLATE_FILE=${REPORT_TEMPLATE_FILE:-templates/report_brazil.md}
    volumes:
      - ./sessions:/app/sessions
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
